# Generated by Django 3.2.13 on 2022-08-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
