# Generated by Django 3.2.13 on 2022-08-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe',
        ),
    ]
