# Generated by Django 3.2.13 on 2022-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoplist',
            name='unique_customer_recipe',
        ),
        migrations.RenameField(
            model_name='shoplist',
            old_name='customer',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='shoplist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_customer_recipe'),
        ),
    ]
