# Generated by Django 3.2.13 on 2022-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_favorite_shoplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipes',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False),
        ),
    ]
